### PR TITLE
Include root node

### PR DESCRIPTION
**Pull request by AaronSadlerUK**
Extended to have an option to include the root node in the sitemap

### CODE REVIEW

**Comment by callumbwhyte** [comment]
Thanks for the PR @AaronSadlerUK!

This is an issue that was also picked up in #2 - something I previously missed due to the way I structure my sites. Definitely a bug that needs fixing!

I'm not entirely sure about the approach you have taken. What is the use case for making this a configuration option? I don't know of a case where the site root shouldn't be included... Maybe you can think of one? 😊

In my opinion, the fix here should be simply changing `DescendantsOrSelf` to `Descendants` on line 39 of `SitemapController`. What do you think?

**Comment by AaronSadlerUK** [comment]
That was my initial thought, but then I figured someone may have a use for this even if I don't.

**Comment by AaronSadlerUK** [comment]
I have also added output caching of 1800 seconds, for larger sitemaps this will save massive overheads each on each request

**Comment by callumbwhyte** [comment]
The package does need a caching mechanism, but this needs to be carefully considered.

We can't cache the whole output of the controller, as the same controller may be used to render multiple sitemaps (based on the domain or configuration).

Furthermore we need a way to purge the sitemap cache on publish, and ensure this is done in a specific enough way that doesn't affect performance of other sitemaps.

Unfortunately I can't accept this pull request in its current form. There are 2 very separate features under this 1 PR that need to be reviewed separately.

If you're willing to submit a new PR with changing `DescendantsOrSelf` to `Descendants` on line 39 of `SitemapController` I will happily accept it.

**Pull request closed without merging**
